// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: fieldday/fieldday.proto

package fieldday

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visitor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First    string `protobuf:"bytes,1,opt,name=First,proto3" json:"First,omitempty"`
	Last     string `protobuf:"bytes,2,opt,name=Last,proto3" json:"Last,omitempty"`
	Callsign string `protobuf:"bytes,3,opt,name=Callsign,proto3" json:"Callsign,omitempty"`
	Youth    bool   `protobuf:"varint,4,opt,name=Youth,proto3" json:"Youth,omitempty"`
	NFARL    bool   `protobuf:"varint,5,opt,name=NFARL,proto3" json:"NFARL,omitempty"`
}

func (x *Visitor) Reset() {
	*x = Visitor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fieldday_fieldday_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Visitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Visitor) ProtoMessage() {}

func (x *Visitor) ProtoReflect() protoreflect.Message {
	mi := &file_fieldday_fieldday_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Visitor.ProtoReflect.Descriptor instead.
func (*Visitor) Descriptor() ([]byte, []int) {
	return file_fieldday_fieldday_proto_rawDescGZIP(), []int{0}
}

func (x *Visitor) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *Visitor) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

func (x *Visitor) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *Visitor) GetYouth() bool {
	if x != nil {
		return x.Youth
	}
	return false
}

func (x *Visitor) GetNFARL() bool {
	if x != nil {
		return x.NFARL
	}
	return false
}

type TotalNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
}

func (x *TotalNum) Reset() {
	*x = TotalNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fieldday_fieldday_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalNum) ProtoMessage() {}

func (x *TotalNum) ProtoReflect() protoreflect.Message {
	mi := &file_fieldday_fieldday_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalNum.ProtoReflect.Descriptor instead.
func (*TotalNum) Descriptor() ([]byte, []int) {
	return file_fieldday_fieldday_proto_rawDescGZIP(), []int{1}
}

func (x *TotalNum) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_fieldday_fieldday_proto protoreflect.FileDescriptor

var file_fieldday_fieldday_proto_rawDesc = []byte{
	0x0a, 0x17, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x64, 0x61, 0x79, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x64, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x64, 0x61, 0x79, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x7b, 0x0a, 0x07, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x46,
	0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4c, 0x61, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x69, 0x67,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x69, 0x67,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x59, 0x6f, 0x75, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x59, 0x6f, 0x75, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x46, 0x41, 0x52, 0x4c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x4e, 0x46, 0x41, 0x52, 0x4c, 0x22, 0x22, 0x0a,
	0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x32, 0xb4, 0x01, 0x0a, 0x08, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61, 0x79, 0x12, 0x33,
	0x0a, 0x0a, 0x61, 0x64, 0x64, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x11, 0x2e, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x64, 0x61, 0x79, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x1a,
	0x12, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x64, 0x61, 0x79, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x4e, 0x75, 0x6d, 0x12, 0x36, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x64,
	0x61, 0x79, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x3b, 0x0a, 0x0c, 0x6c,
	0x69, 0x73, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x64, 0x61, 0x79, 0x2e, 0x56,
	0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x30, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x64, 0x61, 0x79, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x64, 0x61,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fieldday_fieldday_proto_rawDescOnce sync.Once
	file_fieldday_fieldday_proto_rawDescData = file_fieldday_fieldday_proto_rawDesc
)

func file_fieldday_fieldday_proto_rawDescGZIP() []byte {
	file_fieldday_fieldday_proto_rawDescOnce.Do(func() {
		file_fieldday_fieldday_proto_rawDescData = protoimpl.X.CompressGZIP(file_fieldday_fieldday_proto_rawDescData)
	})
	return file_fieldday_fieldday_proto_rawDescData
}

var file_fieldday_fieldday_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fieldday_fieldday_proto_goTypes = []interface{}{
	(*Visitor)(nil),     // 0: fieldday.Visitor
	(*TotalNum)(nil),    // 1: fieldday.TotalNum
	(*empty.Empty)(nil), // 2: google.protobuf.Empty
}
var file_fieldday_fieldday_proto_depIdxs = []int32{
	0, // 0: fieldday.FieldDay.addVisitor:input_type -> fieldday.Visitor
	2, // 1: fieldday.FieldDay.getTotal:input_type -> google.protobuf.Empty
	2, // 2: fieldday.FieldDay.listVisitors:input_type -> google.protobuf.Empty
	1, // 3: fieldday.FieldDay.addVisitor:output_type -> fieldday.TotalNum
	1, // 4: fieldday.FieldDay.getTotal:output_type -> fieldday.TotalNum
	0, // 5: fieldday.FieldDay.listVisitors:output_type -> fieldday.Visitor
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fieldday_fieldday_proto_init() }
func file_fieldday_fieldday_proto_init() {
	if File_fieldday_fieldday_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fieldday_fieldday_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Visitor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fieldday_fieldday_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fieldday_fieldday_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fieldday_fieldday_proto_goTypes,
		DependencyIndexes: file_fieldday_fieldday_proto_depIdxs,
		MessageInfos:      file_fieldday_fieldday_proto_msgTypes,
	}.Build()
	File_fieldday_fieldday_proto = out.File
	file_fieldday_fieldday_proto_rawDesc = nil
	file_fieldday_fieldday_proto_goTypes = nil
	file_fieldday_fieldday_proto_depIdxs = nil
}
